#mkdocs.yml
site_name: Cuadratura Gaussiana
theme: 
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
  - tutorials.md
  - reference.md
  - explanation.md
  - requirements.txt


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

